version: '3'

services:


  nebula-mysql:
     container_name: nebula-cont-mysql
     image: mysql
     build:
        context: ./
        dockerfile: ./mysql/Dockerfile
     environment:
      MYSQL_DATABASE: adventureworks
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: localhost
     ports:
      - "3369:3306"
     #restart: always

  nebula-app:
      image: nebula-springboot
      container_name: nebula-cont-springboot
      #restart: always
      build:
        context: ./
        dockerfile: Dockerfile
      #expose:
        #- "8282"
      ports:
       - "8282:8080"
      depends_on:
        - nebula-mysql
        - rabbitmq-app

  rabbitmq-app:
    image: rabbitmq:3.5.3-management
    build:
     context: ./
     dockerfile: ./rabbit/Dockerfile
    hostname: rabbitmq
    ports:
     - "5666:5672"
     - "15670:15672"
