version: '3'

services:


  nebula-mysql:
     build:
        context: ./
        dockerfile: ./mysql/Dockerfile
     environment:
      MYSQL_DATABASE: adventureworks
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
     ports:
     - "3366:3366"
     restart: always

  nebula-app:
      restart: always
      build:
        context: ./
        dockerfile: Dockerfile
      expose:
        - "8282"
      depends_on:
        - nebula-mysql
        - rabbitmq-app

  rabbitmq-app:
    image: rabbitmq:3.5.3-management
    build:
     context: ./
     dockerfile: ./rabbit/Dockerfile
    hostname: rabbitmq
    ports:
     - 5666:5666
     - 15670:15670
