version: '3'

services:


  nebula-mysql:
     container_name: nebula-cont-mysql
     image: 'mysql:5.7'
     build:
        context: ./
        dockerfile: ./mysql/Dockerfile
     environment:
      MYSQL_DATABASE: adventureworks
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: localhost
      MYSQL_USER : nebula
      MYSQL_PASSWORD: nebula
     ports:
      - "3369:3306"
     #links:
      #- db:db
     #restart: always

  nebula-app:
      image: nebula-springboot
      container_name: nebula-cont-springboot
      #restart: always
      build:
        context: ./
        dockerfile: Dockerfile
      #expose:
        #- "8282"
      ports:
       - "8282:8080"
      depends_on:
        - nebula-mysql
        - nebula-rabbitmq

  nebula-rabbitmq:
      #build: rabbitmq/.
      image: rabbitmq:3.7.5-management
      container_name: nebula-cont-rabbitmq
      #build:
       # context: ./
        #dockerfile: ./rabbit/Dockerfile
      ports:
          - "15673:15672"
          - "5673:5672"


  #rabbitmq-app:
   #  image: "rabbitmq:3-management"
    # container_name: nebula-cont-rabbitmq
     #hostname: "rabbit"
     #ports:
      # - "15673:15672"
       #- "5673:5672"
     #labels:
      # NAME: "rabbitmq"
     #volumes:
      # - ./rabbit/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  #rabbitmq-app:
   # image: rabbitmq:3.5.3-management
    #container_name: nebula-cont-rabbitmq
    #build:
     #context: ./
     #dockerfile: ./rabbit/Dockerfile
    #hostname: rabbitmq
    #ports:
     #- "5666:5672"
     #- "15670:15672"
